baseURL: "https://simplelogin.io/"
languageCode: "en-us"
title: "SimpleLogin | Open source anonymous email service"

enableRobotsTXT: true
canonifyURLs: true
disableKinds:
  - taxonomy
  - taxonomyTerm


# and if you think your md file names or locations might change:
permalinks:
  post: "/blog/:title/"

params:
  description: >
    With email aliases , you can be anonymous online and
    protect your inbox against spams and phishing.
  images:
    - https://simplelogin.io/open-graph.png

markup:
  tableOfContents:
    endLevel: 3
    ordered: true
    startLevel: 3


languages:
  en:
    languageName: "English"
    languageCode: "en_US"
    weight: 1

  fr:
    title: "SimpleLogin | Service de messagerie anonyme open source"
    languageName: "Français"
    languageCode: "fr"
    weight: 2
    params:
      description: >
        Avec les alias d'adresse e-mail, vous pouvez garder votre anonymat en ligne
        et protéger
        votre boite de réception contre les messages de type indésirable/spam et phishing/hameçonnage.
  es:
    languageCode: es
    languageName: Español (España)
    weight: 3
    title: SimpleLogin | Servicio de correo electrónico anónimo de código abierto
    params:
      description: >
        Con alias de correo, puedes ser anónimo en línea y proteger tu buzón contra
        el spam
        y la suplantación de identidad.
  ka:
    languageCode: ka
    languageName: Ქართული (beta)
    weight: 4
    title: SimpleLogin | ღია კოდის მქონე ანონიმური ელფოსტის სერვისი
    params:
      description: >
        ელფოსტის მისამართებით თქვენ, ონლაინ, ანონიმური იქნებით და დაიცავთ თქვენს საფოსტო
        ყუთს სპამისა და ფიშინგისგან.
